In [1]:
import pandas as pd
import numpy as np

In [3]:
class display(object):
    """Display HTML representation of multiple objects"""
    template = """<div style="float: left; padding: 10px;">
    <p style='font-family:"Courier New", Courier, monospace'>{0}</p>{1}
    </div>"""
    def __init__(self, *args):
        self.args = args
        
    def _repr_html_(self):
        return '\n'.join(self.template.format(a, eval(a)._repr_html_())
                         for a in self.args)
    
    def __repr__(self):
        return '\n\n'.join(a + '\n' + repr(eval(a))
                           for a in self.args)

def make_df(cols, ind):
    data = {c: [str(c) + str(i) for i in ind]
            for c in cols}
    return pd.DataFrame(data, ind)

# Relational Algebra

## One to one

In [9]:
df1 = make_df('ABC', range(3))
df2 = make_df('ADE', range(3))
display('df1', 'df2', 'pd.merge(df1, df2)')

df1
    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

df2
    A   D   E
0  A0  D0  E0
1  A1  D1  E1
2  A2  D2  E2

pd.merge(df1, df2)
    A   B   C   D   E
0  A0  B0  C0  D0  E0
1  A1  B1  C1  D1  E1
2  A2  B2  C2  D2  E2