In [64]:
import pandas as pd
import html
class display(object):
    """Display HTML representation of multiple objects"""
    template = """<div style="float: left; padding: 10px;">
    <p style='font-family:"Courier New", Courier, monospace'>{0}</p>{1}
    </div>"""
    def __init__(self, *args):
        self.args = args
        
    def _html_for(self, obj):
        if hasattr(obj, '_repr_html_'):
            try:
                rendered = obj._repr_html_()
                if rendered is not None:
                    return rendered
            except Exception:
                pass
        return '<pre>{}</pre>'.format(html.escape(repr(obj)))
        
    def _repr_html_(self):
        return '\n'.join(self.template.format(a, self._html_for(eval(a)))
                         for a in self.args)
    
    def __repr__(self):
        return '\n\n'.join(a + '\n' + repr(eval(a))
                           for a in self.args)

def make_df(cols, ind):
    data = {c: [str(c) + str(i) for i in ind]
            for c in cols}
    return pd.DataFrame(data, ind)

# introducing pandas string operations

In [65]:
streets = pd.Series(['MaiN st.', 'BroAdway', '1st ave.', 'ElM St.'])
display('streets', 'streets.str.title()', 'streets.str.lower()', 'streets.str.len()')

streets
0    MaiN st.
1    BroAdway
2    1st ave.
3     ElM St.
dtype: str

streets.str.title()
0    Main St.
1    Broadway
2    1St Ave.
3     Elm St.
dtype: str

streets.str.lower()
0    main st.
1    broadway
2    1st ave.
3     elm st.
dtype: str

streets.str.len()
0    8
1    8
2    8
3    7
dtype: int64

can call functions below, as well as many regex functions.

```text
len()         lower()        translate()     islower()
ljust()       upper()        startswith()    isupper()
rjust()       find()         endswith()      isnumeric()
center()      rfind()        isalnum()       isdecimal()
zfill()       index()        isalpha()       split()
strip()       rindex()       isdigit()       rsplit()
rstrip()      capitalize()   isspace()       partition()
lstrip()      swapcase()     istitle()       rpartition()
```

## Regex

In [66]:
streets.str.extract(r'(.*) ').fillna("not found")
display('streets', 'streets.str.extract(r"(.*) ").fillna("not found")')

streets
0    MaiN st.
1    BroAdway
2    1st ave.
3     ElM St.
dtype: str

streets.str.extract(r"(.*) ").fillna("not found")
           0
0       MaiN
1  not found
2        1st
3        ElM

## vectorized item access and slicing

In [67]:
display('streets', 'streets.str[0:2]')

streets
0    MaiN st.
1    BroAdway
2    1st ave.
3     ElM St.
dtype: str

streets.str[0:2]
0    Ma
1    Br
2    1s
3    El
dtype: str

### indicator variables

In [68]:
df = pd.DataFrame({'indicators': ['A|B', 'A|C', 'B|C', 'A|B|C']})
display('df', 'df["indicators"].str.get_dummies("|")')

df
  indicators
0        A|B
1        A|C
2        B|C
3      A|B|C

df["indicators"].str.get_dummies("|")
   A  B  C
0  1  1  0
1  1  0  1
2  0  1  1
3  1  1  1