In [ ]:
import pandas as pd

# introducing pandas string operations

In [6]:
streets = pd.Series(['MaiN st.', 'BroAdway', '1st ave.', 'ElM St.'])
print(streets.str.title())
print(streets.str.lower())
print(streets.str.len())

0    Main St.
1    Broadway
2    1St Ave.
3     Elm St.
dtype: str
0    main st.
1    broadway
2    1st ave.
3     elm st.
dtype: str
0    8
1    8
2    8
3    7
dtype: int64

can call functions below, as well as many regex functions.

```text
len()         lower()        translate()     islower()
ljust()       upper()        startswith()    isupper()
rjust()       find()         endswith()      isnumeric()
center()      rfind()        isalnum()       isdecimal()
zfill()       index()        isalpha()       split()
strip()       rindex()       isdigit()       rsplit()
rstrip()      capitalize()   isspace()       partition()
lstrip()      swapcase()     istitle()       rpartition()
```

## Regex

In [17]:
streets.str.extract(r'(.*) ').fillna("not found")

           0
0       MaiN
1  not found
2        1st
3        ElM

## vectorized item access and slicing

In [18]:
streets.str[0:2]

0    Ma
1    Br
2    1s
3    El
dtype: str

### indicator variables

In [20]:
streets['indicators'] = pd.Series(['A|B', 'A|C', 'B|C', 'A|B|C'])
streets['indicators'].str.get_dummies('|')

   A  B  C
0  1  1  0
1  1  0  1
2  0  1  1
3  1  1  1